################################################################
# This is the PRODUCTION config file.
#
# Run this command when ready to deploy/upload to your server:
# `jekyll build`
#
# This file is *NOT* rebuilt automatically.
# If you change this file, please restart the server process
###############################################################
#
# Welcome to Jekyll+Rohbau!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Additional resources:
# * https://frontendchecklist.com/
# * https://images.guide/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see  them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nacht des Heiligtums
email: info@nacht-des-heiligtums.de
description: >-
  Die Nacht des Heiligtums ist das Jugendfestival der Schönstattjugend in Deutschland.
tagline: Verbum domini manet in eternum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

locale: de-DE
timezone: Europe/Berlin

backend:
  name: git-gateway
  roles: [Admin]
  repo: nacht-des-heiligtums/nachtdesheiligtums.de

identity_provider: netlify

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-paginate
  - jekyll-git_metadata
  - i18n

source: source
destination: _build
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: bsquo,lsquo,bdquo,ldquo
  enable_coderay: false

# Sass Processing
sass:
  style: compressed

collections:
  ndhs:
    output: true
    permalink: /nacht:name

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
    section: artikel
    permalink: "/artikel/:year-:month-:day-:slug/"
    read_time: false
- scope:
    path: ""
    type: events
  values:
    layout: event

# # Settings for _includes/head/theme.html:
#
# Value for application-name meta tag
# application_name:
#
# Set to true to inject touch icon paths in head
# appicons: true
#
# Set theme-color meta tag
# theme_color: #235412
#

# # Settings for _includes/head/metadata.html:

# Set separator for site title:
# title_separator: " | "
#
# For pages:
# * author: name of author
# * date: publication date
# * image.cover: over image
#
# Twitter:
# twitter:
#   username:
#
# Facebook:
# facebook:
#   admins:
#   publisher:
#   app_id:
#   name: # default: site.title
#
# Verifications for several webmaster tools:
webmaster_verification:
  google:
  bing:
  alexa:
  yandex:

# # Settings for impressum.html
impressum:
  name: >
    Schönstatt-Bewegung Deutschland e.V. – Nacht des Heiligtums
    Sr. M. Anastasia Brand
  address: >
    Hillscheider Straße 7
    56179 Vallendar
  email: kontakt@nachtdesheiligtums.de
  fon: 0261 / 65 06 1336

