################################################################
# This is the DEVELOPMENT config file.
# Any settings here will override those in _config.yml
#
# Run this command to work locally:
# `bin/serve dev`
#
# If you change this file, please restart the server process
###############################################################

baseurl: "" # ex: `/project` if serving from `http://localhost:4000/project/`
url: "http://localhost:8310/" # the base hostname & protocol for your site (can leave it blank for local dev)

# Disable index building
lsi: false

# Environment - use this in your logic:
# {% if site.environment == "development" %} do things {% endif %}
environment: "development"
port: 8310
host: 0.0.0.0

# livereload
livereload: true

# Sass Processing
sass:
  style: expanded # options: nested, compact, expanded, compressed
