---
sitemap: false
---
backend:
  name: "{{ site.backend.name }}"
  repo: "{{ site.backend.repo }}" # Path to your Github repository
  branch: "{{ site.backend.branch | default: 'master' }}" # Branch to update (master by default)

media_folder: "source/assets/uploads" # Folder where user uploaded files should go
public_folder: "assets/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artikel" # Used in the UI, ie.: "New Post"
    folder: "source/_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is Titel:asc
    create: true # Allow users to create new documents in this collection
    slug: {% raw %}"{{year}}-{{month}}-{{day}}-{{slug}}"{% endraw %}
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titel", name: "title", widget: "string", tagname: "h1"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Jahr", name: "ndh", widget: "string", default: "2018"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "ndh"
    label: "NdHs"
    folder: "source/_ndhs"
    sort: "slug"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string", tagname: "h1"}
      - {label: "Motto", name: "motto", widget: "string", tagname: "h2"}
      - {label: "Datum", name: "datum", widget: "string"}
      - {label: Intro, name: intro, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Description, name: description, widget: markdown},
          {label: Blurbs, name: blurbs, widget: list, fields: [
            {label: Image, name: image, widget: image},
            {label: Text, name: text, widget: text},
            {label: URL, name: url, widget: string}
          ]}
        ]}
      - {label: "Text", name: "body", widget: "markdown"}
      - {name: "layout", widget: "hidden", required: false, default: "event"}
  - name: "pages"
    label: "Seiten"
    sort: "slug"
    create: false
    delete: false
    files:
      - label: "Home"
        name: "index"
        file: "source/index.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {name: "body", widget: "hidden", required: false}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
        - label: "Inhalt"
          name: "intro"
          widget: "object"
          fields:
          - {label: "Blurbs", label_singular: "Blurb", name: "blurbs", widget : "list", fields: [
              {name: "text", label: "Titel", widget: "string"},
              {name: "url", label: "URL", widget: "string"},
              {name: "image", label: "Bild", widget: "image"}
            ]}
          - {label: "Beschreibung", name: "description", widget: "markdown"}
      - label: "Kernteam"
        name: "kernteam"
        file: "source/_pages/kernteam.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
        - {name: "testimonials", label: "Testimonials", label_singular: "Testimonial", required: false, widget: "list", fields: [
            {name: "name", label: "Name", widget: "string", tagname: "strong"},
            {name: "image", label: "Bild", widget: "file", tagname: "img"},
            {name: "quote", label: "Zitat", widget: "text"}
          ]}
      - label: "Anreise"
        name: "anreise"
        file: "source/_pages/anreise.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Helferwoche"
        name: "helferwoche"
        file: "source/_pages/helferwoche.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Sponsoring"
        name: "sponsoring"
        file: "source/_pages/sponsoring.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Die Nacht des Heiligtums"
        name: "die-nacht-des-heiligtums"
        file: "source/_pages/idee.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Schönstatt"
        name: "schoenstatt"
        file: "source/_pages/schoenstatt.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Einverständniserklärung"
        name: "einverständniserklärung"
        file: "source/_pages/einverständniserklärung.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {name: "title", label: "Titel", widget: "string", tagname: "h1"}
        - {name: "body", label: "Text", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
      - label: "Workshops"
        name: "workshops"
        file: "source/_pages/workshops.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {name: "title", label: "Titel", widget: "string", tagname: "h1"}
        - {name: "body", label: "Text", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
      - label: "Spenden"
        name: "spenden"
        file: "source/_pages/spenden.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - {label: "Text", name: "body", widget: "markdown"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
        - {name: "images", widget: "hidden", required: false}
      - label: "Summer of Revolution"
        name: "summer-of-revolution"
        file: "source/_pages/summer-of-revolution.md"
        fields:
        - {name: "layout", widget: "hidden", required: false}
        - {name: "title", label: "Titel", widget: "string", tagname: "h1"}
        - {name: "body", label: "Text", widget: "markdown"}
        - name: "entries"
          label: "Einträge"
          label_singular: "Eintrag"
          required: false
          widget: "list"
          fields: [
          - {name: "title", label: "Titel", widget: "string", tagname: "strong"}
          - { name: "datum", label: "Datum", widget: "string"}
          - {name: "image", label: "Bild", widget: "file", tagname: "img"}
          - {name: "file", label: "Datei", widget: "file", tagname: "a"}
          - {name: "description", label: "Beschreibung", widget: "text"}
        - {name: "permalink", widget: "hidden", required: false}
        - {name: "sitemap", widget: "hidden", required: false}
